### ISSUE TITLE
docker镜像1.18.26存在问题

### ISSUE THREAD

**Issue by ooo176** [wojiushixiaobai/dataease#3]
执行
docker run -d  -e DB_HOST=xxx -e DB_PORT=3306 -e DB_USER=root -e DB_PASSWORD=xxx -e DB_NAME=dataease_v1 --name dataease_v1 -p 8101:8100  wojiushixiaobai/dataease:v1.18.24

一直报错：

essors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor [schedulerStarter]? Check the corresponding BeanPostProcessor declaration and its dependencies.
2024-12-16 08:17:58.691 WARN  --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'flyway' of type [org.flywaydb.core.Flyway] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected into a currently created BeanPostProcessor [schedulerStarter]? Check the corresponding BeanPostProcessor declaration and its dependencies.
2024-12-16 08:17:58.731 INFO  --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2024-12-16 08:17:58.993 INFO  --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@27b7204
2024-12-16 08:17:58.996 INFO  --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2024-12-16 08:17:59.068 INFO  --- [           main] org.flywaydb.core.FlywayExecutor         : Database: jdbc:mysql://192.168.137.139:3306/dataease_v1 (MySQL 8.0)
2024-12-16 08:17:59.174 INFO  --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema `dataease_v1`: 2.10.3
2024-12-16 08:17:59.175 WARN  --- [           main] o.f.core.internal.command.DbMigrate      : outOfOrder mode is active. Migration of schema `dataease_v1` may not be reproducible.
2024-12-16 08:17:59.199 WARN  --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'schedulerStarter': Unsatisfied dependency expressed through field 'scheduler': Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Schema `dataease_v1` contains a failed migration to version 2.10.3 !
2024-12-16 08:17:59.199 INFO  --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2024-12-16 08:17:59.207 INFO  --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2024-12-16 08:17:59.225 INFO  --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-12-16 08:17:59.265 ERROR --- [           main] o.springframework.boot.SpringApplication : Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'schedulerStarter': Unsatisfied dependency expressed through field 'scheduler': Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Schema `dataease_v1` contains a failed migration to version 2.10.3 !
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:787)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:767)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:508)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1421)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:277)
        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:805)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
        at io.dataease.CoreApplication.main(CoreApplication.java:15)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.PropertiesLauncher.main(PropertiesLauncher.java:574)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Schema `dataease_v1` contains a failed migration to version 2.10.3 !

**Comment by wojiushixiaobai** [comment]
`v1` 还是用官方的说明部署下，v1 如果我没记错的话 **数据库** 信息是不支持自定义的。

**Comment by ooo176** [comment]
> `v1` 还是用官方的说明部署下，v1 如果我没记错的话 **数据库** 信息是不支持自定义的。

都试了，用了官方的数据库dataease，也是报这个错，是不是镜像本身的问题

**Comment by wojiushixiaobai** [comment]
我的意思是你按照官方的文档操作下，如果还是一样的问题那可能就是版本有问题，使用新版本再试试。

**Comment by weifengit** [comment]
# 大佬，您好，我才是真小白
1. 我在docker compose up -d之前去修改docker-compose.yml中mysql的密码，总是报如下检查不健康的错误，您提供的密码太长了，小白不喜欢；
2. 还有，我想在宿主机连接数据库，一直连不上，自己捣鼓在docker-compose.yaml文件中加入了端口映射，就OK了，建议加上

`[+] Running 2/2
 ✘ Container de_mysql  Error                                                                                                            50.7s 
 ✔ Container de_core   Created                                                                                                           0.0s 
dependency failed to start: container de_mysql is unhealthy`

**Comment by wojiushixiaobai** [comment]
@weifengit 数据库默认是不需要对外开放的。
自定义配置文件你可以参考下面的方法：
```sh
cd ~
git clone --depth=1 https://github.com/wojiushixiaobai/dataease
```
```sh
cd ~/dataease

cp config-example.txt .env
vim. env

# 版本号可以自己根据项目的版本修改
VERSION=v2.10.5

# Compose
COMPOSE_PROJECT_NAME=de
# COMPOSE_HTTP_TIMEOUT=3600
# DOCKER_CLIENT_TIMEOUT=3600

# 持久化存储
VOLUME_DIR=/data/dataease

# 时区
TZ=Asia/Shanghai

# MySQL 
DB_HOST=mysql
DB_PORT=3306
DB_USER=root
# 如果需要修改密码修改下面的 DB_PASSWORD=<自定义数据库密码> 即可
# 比如 DB_PASSWORD=Weakpassword
DB_PASSWORD=nu4x599Wq7u0Bn8EABh3J91G
DB_NAME=dataease

# Web 端口
HTTP_PORT=8100
```
```sh
docker compose config
docker compose up -d
```

通过 `.env` 文件来自定义变量，不需要直接修改 `docker-compose.yml`

**Comment by weifengit** [comment]
✔ Network de_net      Created                                                                                                           0.0s 
 ⠸ Container de_mysql  Starting                                                                                                          0.3s 
 ✔ Container de_core   Created                                                                                                           0.0s 
Error response from daemon: Mounts denied: 
The path /data/dataease/mariadb/data is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/settings/mac/#file-sharing for more info.

**Comment by wojiushixiaobai** [comment]
>  ✔ Network de_net      Created                                                                                                           0.0s 
>  ⠸ Container de_mysql  Starting                                                                                                          0.3s 
>  ✔ Container de_core   Created                                                                                                           0.0s 
> Error response from daemon: Mounts denied: 
> The path /data/dataease/mariadb/data is not shared from the host and is not known to Docker.
> You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
> See https://docs.docker.com/desktop/settings/mac/#file-sharing for more info.

持久化目录存储权限问题需要自己解决，可以将该目录更换成有权限的路径

**Comment by weifengit** [comment]
好的，谢谢大神，我已解决持久化的问题,可以正常部署了，然后还有一个情况想跟您反馈一下：
我一开始没用git下载，直接下载zip压缩包，解压之后看到config-example.txt文件里面显示的2.10.0版本（不是目前最新的2.10.5版本），如果用2.10.0这个版本，127.0.0.1:8100 一直刷不出来dataease主页，然后我用git clone到本地，最新的版本则可以进入dataease主页面

**Comment by wojiushixiaobai** [comment]
> 好的，谢谢大神，我已解决持久化的问题,可以正常部署了，然后还有一个情况想跟您反馈一下：
> 我一开始没用git下载，直接下载zip压缩包，解压之后看到config-example.txt文件里面显示的2.10.0版本（不是目前最新的2.10.5版本），如果用2.10.0这个版本，127.0.0.1:8100 一直刷不出来dataease主页，然后我用git clone到本地，最新的版本则可以进入dataease主页面

版本号也可以在.env 里面自定义，升级的时候直接改版本号启动就能完成升级，不能降级自己做好备份
